spring:
  application:
    name: monitor-client
  zipkin:
    baseUrl: http://localhost:8095
server:
  port: ${PORT:8080}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

