spring:
  application:
    name: monitor-server
  zipkin:
      baseUrl: http://localhost:8095
server:
  port: ${PORT:8095}
zipkin:
  web:
    rootUrl: /zipkin/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
turbine:
  aggregator:
    clusterConfig: MONITOR
  appConfig: monitor-client, monitor-server